#!/bin/sh
# $Revision$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# * Neither the name of the Nth Dimension nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# (c) Tim Brown, 2014
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>

if [ -z "${classdumpincluded}" ]
then

classdumpincluded=1

. lib/misc/file
. lib/misc/stdio
. lib/misc/binary

classdump_check_or_classdump () {
	[ "`file_is_regular "\`basename "${FILENAME}"\`.decrypted.$$"`" ] || false
	if [ "`file_is_directory "\`basename "${FILENAME}"\`.classdump.$$"`" -ne 1 ]
	then
		stdio_message_log "classdump" "Generating classdump..."
		mkdir "`basename "${FILENAME}"`.classdump.$$"
		class-dump-z -y /var/iPhoneOS7.1.sdk -H -o "`basename "${FILENAME}"`.classdump.$$" "`basename "${FILENAME}"`.decrypted.$$"
		stdio_message_log "classdump" "Classdump generated..."
	fi
}

classdump_list () {
	find "`basename "${FILENAME}"`.classdump.$$" -type f
}

classdump_matches_ios_api () {
	filename="${1}"
	searchstring="${2}"
	[ "`file_is_regular "${filename}"`" ] || false
	[ "`validate_is_string "${searchstring}"`" ] || false
	egrep -oh "${searchstring}" "${filename}" | sort | uniq | xargs | tr " " ","
}

classdump_check_or_classdump

fi
