#!/bin/sh
# $Revision$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# * Neither the name of the Nth Dimension nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# (c) Tim Brown, 2015
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
#  Check if binary files call AFNetworking functions

. lib/misc/stdio
. lib/misc/file
. lib/misc/binary

binary_afnetworking_init() {
	stdio_message_log "binary_afnetworking" "Starting at: $(date)"
}

binary_afnetworking_main() {
	binary_list | while read filename
	do
		binary_afnetworking_apis="$(binary_matches_api "${filename}" "setAllowInvalidCertificates|allowsInvalidSSLCertificate")"
		if [ -n "${binary_afnetworking_apis}" ]
		then
			stdio_message_warn "binary_afnetworking" "${filename} uses AFNetworking APIs to allow invalid certificates (${binary_afnetworking_apis})"
		fi
		if [ -z "$(binary_matches_api "${filename}" "validatesDomainName")" ]
		then
			stdio_message_warn "binary_afnetworking" "${filename} does not use AFNetworking APIs to force hostname validation"
		fi
		if [ -z "$(binary_matches_api "${filename}" "SSLPinningMode")" ]
		then
			stdio_message_warn "binary_afnetworking" "${filename} does not use AFNetworking APIs for pinning"
		fi
	done
}

binary_afnetworking_fini() {
	stdio_message_log "binary_afnetworking" "Ending at: $(date)"
}
