#!/bin/sh
# $Revision$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# * Neither the name of the Nth Dimension nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# (c) Tim Brown, 2014
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check if binary files call functions to check for configuration profile (useful if it's a private app managed through an MDM)

. lib/misc/stdio
. lib/misc/binary

binary_configuration_profile_init () {
	stdio_message_log "binary_configuration_profile" "Starting at: $(date)"
}

binary_configuration_profile_main () {
	binary_list | while read filename
	do
		if [ -n "$(binary_matches_api "${filename}" "SecCertificateCreateWithData")" ]
		then
			if [ -n "$(binary_matches_api "${filename}" "SecTrustCreateWithCertificates")" ]
			then
				if [ -n "$(binary_matches_api "${filename}" "SecTrustEvaluate")" ]
				then
					stdio_message_log "binary_configuration_profile" "${filename} may use APIs to check for configuration profile"
				else
					stdio_message_warn "binary_configuration_profile" "${filename} does not use APIs to check for configuration profile"
				fi
			else
				stdio_message_warn "binary_configuration_profile" "${filename} does not use APIs to check for configuration profile"
			fi
		else
			stdio_message_warn "binary_configuration_profile" "${filename} does not use APIs to check for configuration profile"
		fi
	done
}

binary_configuration_profile_fini () {
	stdio_message_log "binary_configuration_profile" "Ending at: $(date)"
}
