#!/bin/sh
# $Revision$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# * Neither the name of the Nth Dimension nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# (c) Tim Brown, 2014
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check if binary files call crypto functions

. lib/misc/stdio
. lib/misc/classdump

classdump_crypto_init () {
	stdio_message_log "classdump_crypto" "Starting at: $(date)"
}

classdump_crypto_main () {
	classdump_list | while read filename
	do
		crypto_apis="$(classdump_matches_ios_api "${filename}" "CCryptorRef")"
		if [ -n "${crypto_apis}" ]
		then
			stdio_message_log "classdump_crypto" "${filename} uses crypto APIs (${crypto_apis})"
		fi
		weak_crypto_apis="$(classdump_matches_ios_api "${filename}" "DES|3ES|RC2|RC4|ECB|CBC")"
		if [ -n "${weak_crypto_apis}" ]
		then
			stdio_message_log "classdump_crypto" "${filename} may use weak crypto APIs (${weak_crypto_apis})"
		fi
		strong_crypto_apis="$(classdump_matches_ios_api "${filename}" "AES|CAST|RSA")"
		if [ -n "${strong_crypto_apis}" ]
		then
			stdio_message_log "classdump_crypto" "${filename} may use strong crypto APIs (${strong_crypto_apis})"
		fi
		# TODO RSA
	done
}

classdump_crypto_fini () {
	stdio_message_log "classdump_crypto" "Ending at: $(date)"
}
